[project]
name = "cs50-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "samchouhan", email = "sakshamchouhan8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
cs50-ai = "cs50_ai:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
